### ISSUE TITLE
Buffering the events in HttpAppender will miss last msg(s) in the event the application exits unexpectedly

### ISSUE THREAD

**Issue by bpmcd** [phdata/pulse#23]
Also, it seems like msgs will sit in the buffer until the next message is added.  Depending on how long that delay is, we could have a message in the buffer for potentially longer than is desirable.

HttpAppender#flush() can only be called from append(event) or close().  It's possible for events to be in the buffer for multiple minutes or more.

**Comment by afoerster** [comment]
> Buffering the events in HttpAppender will miss last msg(s) in the event the application exits unexpectedly
This should be handled by the jvm shutdown hook and immediate flushing of error messages. There are still probably cases like OOM that might not be covered here but not sure there's much we can do about that.

> Also, it seems like msgs will sit in the buffer until the next message is added. Depending on how long that delay is, we could have a message in the buffer for potentially longer than is desirable.
Maybe set up a background thread check if a flush is needed every second or two here?
